version: '3'

services:
  php:
    build: .
    volumes:
      - .:/opt/app
    ports:
      - 8000:8000
    env_file:
      - .env
    links:
      - db
  db:
    image: mariadb:10.1.34
    ports:
      - 3306:3306
    env_file:
      - .env
